#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

# Check if we are moving between branches (3rd argument is 1). If not, it's likely just a file checkout.
if [ "$3" = "1" ]; then
    echo "Switched branches! Reinstalling npm packages..."
    npm ci
fi
